### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by jaswilli** [comment]
Hi--Are you planning on merging this for grunt 1.0 compatibility?

**Comment by jlsutherland** [comment]
Ah, there we go.

**Comment by jaswilli** [comment]
@jlsutherland When you have time could I trouble you to do a version bump and release so we can pull this change in from npm?  Thanks.

**Comment by jlsutherland** [comment]
Sorry, this fell through the cracks. Let me do for you now @jaswilli

**Comment by jlsutherland** [comment]
@jaswilli You're all set. Thanks for your patience.

**Comment by jaswilli** [comment]
No worries!  Thanks for taking the time do this.

**Pull request merged**
