### PR TITLE
Add support for port number on debug and debug-brk, add docs and changelog.

### PR DESCRIPTION
**Pull request by vibegui**
@paulpflug @ericclemmons @justcfx2u can you take this for a spin? It addresses the problems discussed on the previous merge.

### CODE REVIEW

**Comment by ericclemmons** [comment]
Holy crap, I am _way_ behind on this.  Tagged & released.

Is there a way to add someone else with publishing permissions on NPM?  Ping me if so...

**Comment by firstdoit** [comment]
Yep. For example:

    npm owner add firstdoit

**Comment by ericclemmons** [comment]
@firstdoit: Alright, so you officially_accept_ collaborator rights? :D

**Comment by firstdoit** [comment]
Yessir :star2: :)

**Pull request merged**
