### PR TITLE
Added Node v8 support

### PR DESCRIPTION
**Pull request by gintsgints**
Node v8 has --debug option depricated. --inspect should be used instead

### CODE REVIEW

**Comment by trauma2u** [comment]
@gintsgints Good job. Thanks :)
@ericclemmons Merge the pull request please.

**Comment by jlsutherland** [comment]
Thanks both!

**Comment by trauma2u** [comment]
@jlsutherland Thanks a lot!
To use the package via npm, it should be versioned up to v0.5.4 and published to npm...
Could you help me with this?

**Comment by jlsutherland** [comment]
@trauma2u Done.

**Comment by trauma2u** [comment]
@jlsutherland Thanks!

**Pull request merged**
